### ISSUE TITLE
Python 3 Support/Exception Syntax

### ISSUE THREAD

**Issue by stringsonfire** [whosonfirst/py-mapzen-whosonfirst-utils#14]
Are you supporting Python 3?

If so, I get:
```
(ENV) C:\Program Files\Python35\Scripts>python wof-spatial-index
Traceback (most recent call last):
  File "wof-spatial-index", line 4, in <module>
    __import__('pkg_resources').run_script('mapzen.whosonfirst.spatial==0.12', 'wof-spatial-index')
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources\__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources\__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "C:\Program Files\Python35\lib\site-packages\mapzen.whosonfirst.spatial-0.12-py3.5.egg\EGG-INFO\scripts\wof-spatial-index", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
  File "C:\Program Files\Python35\lib\site-packages\mapzen.whosonfirst.utils-0.31-py3.5.egg\mapzen\whosonfirst\utils\__init__.py", line 51
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

It'd need to be `as e`, supporting 2.6 upwards and 3.x. I've seen this dotted around elsewhere as well.

**Comment by thisisaaronland** [comment]
Currently everything is targeting 2.7.x

**Comment by stantond** [comment]
I think this is the only thing that breaks compatibility. Given `as` works from 2.6 onwards, worth moving to this?

**Comment by thisisaaronland** [comment]
It is worth moving to Python 3 for sane Unicode support, if nothing else. Given the volume of Python 2.x code we are running in production though it will require a measure of testing that we'll have to schedule with everything else.

As a short-term stop-gap are you able to install Python 2.x alongside 3.x ?

**Comment by stantond** [comment]
Sure, I can play with this in a separate virtual environment for now

**Comment by stantond** [comment]
I'll wait for the fix for [py-mapzen-whosonfirst-spatial issue 6](https://github.com/whosonfirst/py-mapzen-whosonfirst-spatial/issues/6) then give it a go.
