### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2'

### ISSUE THREAD

**Issue by Platzii** [whosonfirst/py-mapzen-whosonfirst-utils#21]
Hi

I've pulled the latest version of the code today and bumped on this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/wof-placetype-to-csv", line 4, in <module>
    __import__('pkg_resources').run_script('mapzen.whosonfirst.utils==0.384-', 'wof-placetype-to-csv')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mapzen.whosonfirst.utils-0.384_-py2.7.egg/EGG-INFO/scripts/wof-placetype-to-csv", line 142
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/mapzen.whosonfirst.utils-0.384_-py2.7.egg/EGG-INFO/scripts/wof-placetype-to-csv on line 142, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

When I open the file on line 142 in vim I see these chars: `�~@~S` (as you can see below)
Replacing it with a `-` fixes the problem.

Could you check this out please?

Kind regards
Simon

![screen shot 2017-03-05 at 20 27 24](https://cloud.githubusercontent.com/assets/7767841/23590546/47e587d8-01e2-11e7-8ed9-5fb73af68d60.png)

**Comment by thisisaaronland** [comment]
This is the thing I love the most about Python...

It should be fixed now and apologies for that.
